### PR TITLE
Update tini.js

### PR DESCRIPTION
**Pull request by XtremePlayzCODE**

### CODE REVIEW

**Comment by SharkFinPro** [comment]
Is this ready?

**Comment by XtremePlayzCODE** [comment]
should be, but i'm trying to make a 3D engine with stunning graphics. not going well.

**Comment by SharkFinPro** [comment]
should we use foreach, or use a for loop @XtremePlayzCODE

**Comment by XtremePlayzCODE** [comment]
for loop to avoid older browser compatibility and to keep polyfills out (which will increase code size, making the name "Tini" not so right)

**Comment by SharkFinPro** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
push?

**Comment by SharkFinPro** [comment]
ye

**Pull request merged**
